---
apiVersion: batch/v1
kind: Job
metadata:
  name: hello
  namespace: one
spec:
  template:
    spec:
      containers:
      - args:
        - -c
        - echo hello from namespace one
        image: bash
        name: hello
